### PR TITLE
Chat layout

### PR DESCRIPTION
**Pull request by jasonheeps**
- reduced "learning group box" to a simple button
- new messages get added at the top
- position of chatbox is sticky
- chat is enabled by default with the option to hide it (couldn't figure out another way since sending a message reloads the page and then you want the chat to be displayed after you've just sent a message)
- chat only shows the last 3 messages
- chat scrollbar only activated on y-axis on hover and only if needed
chat_layout

### CODE REVIEW

**Comment by sabinacuccibar** [comment]
I love it!

**Review by sabinacuccibar — APPROVED** [review]
It's very very nice. Do not forget to position it in the right place, not super close to the steps divs

**Comment by jasonheeps** [comment]
> It's very very nice. Do not forget to position it in the right place, not super close to the steps divs

It's in the middle of the right-side container, like this
image

**Comment by sabinacuccibar** [comment]
😍
*Sabina Barcucci *Architect
WORKS
<https://drive.google.com/file/d/1k6O6IAFnJPIcF0iTHUxykiijgmSLN749/view> /
LINKEDIN <https://www.linkedin.com/in/sabinabarcucci/>



*CREATIVE FORMATS *
*FOR POST-DIGITAL CROWDS *
*design / culture / **innovation *
+39 339 3237 935
***@***.***
Via Stazio 11, 20131 Milan

This message (including any attachments) is intended exclusively for the
use of the individual or entity to which it is addressed and may contain
information that is confidential, proprietary, privileged, non-public and
exempt from disclosure. If you are not the intended recipient, you are
prohibited from any use, dissemination, distribution or copying of the
information contained in this message. If you have received this
communication by mistake, please notify us and delete this message and its
attachments immediately. Thank you.


Questo messaggio e-mail è riservato unicamente al/ai soggetto/i
destinatario/i e può contenere informazioni riservate e/o coperte da
segreto professionale utilizzabili esclusivamente dal/i destinatario/i
sopraindicato/i. Il ricevente, se diverso dal destinatario, è avvertito che
qualsiasi utilizzazione, divulgazione o copia di questa comunicazione,
nonché di eventuali suoi allegati, comporta la violazione delle
disposizioni di Legge sulla tutela dei dati personali (D. Lgs 196/2003).
Qualora il messaggio fosse ricevuto per errore, si prega di cancellarlo e
distruggere eventuali copie o stampe e di darne informazione immediata al
mittente. Grazie.

**Review by KseniiaNovinskaia — APPROVED** [review]

**Pull request merged**
